AllCops:
  UseCache: false
  DisplayCopNames: true
  Exclude:
    - !ruby/regexp /\/db\/schema\.rb$/
    - !ruby/regexp /\/vendor\/.*/
    - !ruby/regexp /\/bin\/.*/
    - db/migrate/*
    - config/puma.rb
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
