# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b72ee0ab775aa12b1481aea3a7605d26fdf40fe24bd92c859c002a165d622c626ffda23bc12cf5d3c94a7b0ee2758dfa773763f3b36b3cfc92c54fccecafb7

test:
  secret_key_base: 55f15c6df234184560565d1dd9ba99b7700c59cde67028880bef10863075416803e28ef5a83b90ca3358fb89b8978d48e0dbed5dfd5acce9cd8bdc9600b1db0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
